<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $cities = [
            [1, 1, '15 مايو', '15 May', 'EGY'],
            [2, 1, 'الازبكية', 'Al Azbakeyah', 'EGY'],
            [3, 1, 'البساتين', 'Al Basatin', 'EGY'],
            [4, 1, 'التبين', 'Tebin', 'EGY'],
            [5, 1, 'الخليفة', 'El-Khalifa', 'EGY'],
            [6, 1, 'الدراسة', 'El darrasa', 'EGY'],
            [7, 1, 'الدرب الاحمر', 'Aldarb Alahmar', 'EGY'],
            [8, 1, 'الزاوية الحمراء', 'Zawya al-Hamra', 'EGY'],
            [9, 1, 'الزيتون', 'El-Zaytoun', 'EGY'],
            [10, 1, 'الساحل', 'Sahel', 'EGY'],
            [11, 1, 'السلام', 'El Salam', 'EGY'],
            [12, 1, 'السيدة زينب', 'Sayeda Zeinab', 'EGY'],
            [13, 1, 'الشرابية', 'El Sharabeya', 'EGY'],
            [14, 1, 'مدينة الشروق', 'Shorouk', 'EGY'],
            [15, 1, 'الظاهر', 'El Daher', 'EGY'],
            [16, 1, 'العتبة', 'Ataba', 'EGY'],
            [17, 1, 'القاهرة الجديدة', 'New Cairo', 'EGY'],
            [18, 1, 'المرج', 'El Marg', 'EGY'],
            [19, 1, 'عزبة النخل', 'Ezbet el Nakhl', 'EGY'],
            [20, 1, 'المطرية', 'Matareya', 'EGY'],
            [21, 1, 'المعادى', 'Maadi', 'EGY'],
            [22, 1, 'المعصرة', 'Maasara', 'EGY'],
            [23, 1, 'المقطم', 'Mokattam', 'EGY'],
            [24, 1, 'المنيل', 'Manyal', 'EGY'],
            [25, 1, 'الموسكى', 'Mosky', 'EGY'],
            [26, 1, 'النزهة', 'Nozha', 'EGY'],
            [27, 1, 'الوايلى', 'Waily', 'EGY'],
            [28, 1, 'باب الشعرية', 'Bab al-Shereia', 'EGY'],
            [29, 1, 'بولاق', 'Bolaq', 'EGY'],
            [30, 1, 'جاردن سيتى', 'Garden City', 'EGY'],
            [31, 1, 'حدائق القبة', 'Hadayek El-Kobba', 'EGY'],
            [32, 1, 'حلوان', 'Helwan', 'EGY'],
            [33, 1, 'دار السلام', 'Dar Al Salam', 'EGY'],
            [34, 1, 'شبرا', 'Shubra', 'EGY'],
            [35, 1, 'طره', 'Tura', 'EGY'],
            [36, 1, 'عابدين', 'Abdeen', 'EGY'],
            [37, 1, 'عباسية', 'Abaseya', 'EGY'],
            [38, 1, 'عين شمس', 'Ain Shams', 'EGY'],
            [39, 1, 'مدينة نصر', 'Nasr City', 'EGY'],
            [40, 1, 'مصر الجديدة', 'New Heliopolis', 'EGY'],
            [41, 1, 'مصر القديمة', 'Masr Al Qadima', 'EGY'],
            [42, 1, 'منشية ناصر', 'Mansheya Nasir', 'EGY'],
            [43, 1, 'مدينة بدر', 'Badr City', 'EGY'],
            [44, 1, 'مدينة العبور', 'Obour City', 'EGY'],
            [45, 1, 'وسط البلد', 'Cairo Downtown', 'EGY'],
            [46, 1, 'الزمالك', 'Zamalek', 'EGY'],
            [47, 1, 'قصر النيل', 'Kasr El Nile', 'EGY'],
            [48, 1, 'الرحاب', 'Rehab', 'EGY'],
            [49, 1, 'القطامية', 'Katameya', 'EGY'],
            [50, 1, 'مدينتي', 'Madinty', 'EGY'],
            [51, 1, 'روض الفرج', 'Rod Alfarag', 'EGY'],
            [52, 1, 'شيراتون', 'Sheraton', 'EGY'],
            [53, 1, 'الجمالية', 'El-Gamaleya', 'EGY'],
            [54, 1, 'العاشر من رمضان', '10th of Ramadan City', 'EGY'],
            [55, 1, 'الحلمية', 'Helmeyat Alzaytoun', 'EGY'],
            [56, 1, 'النزهة الجديدة', 'New Nozha', 'EGY'],
            [57, 1, 'العاصمة الإدارية', 'Capital New', 'EGY'],
            [58, 2, 'الجيزة', 'Giza', 'EGY'],
            [59, 2, 'السادس من أكتوبر', 'Sixth of October', 'EGY'],
            [60, 2, 'الشيخ زايد', 'Cheikh Zayed', 'EGY'],
            [61, 2, 'الحوامدية', 'Hawamdiyah', 'EGY'],
            [62, 2, 'البدرشين', 'Al Badrasheen', 'EGY'],
            [63, 2, 'الصف', 'Saf', 'EGY'],
            [64, 2, 'أطفيح', 'Atfih', 'EGY'],
            [65, 2, 'العياط', 'Al Ayat', 'EGY'],
            [66, 2, 'الباويطي', 'Al-Bawaiti', 'EGY'],
            [67, 2, 'منشأة القناطر', 'ManshiyetAl Qanater', 'EGY'],
            [68, 2, 'أوسيم', 'Oaseem', 'EGY'],
            [69, 2, 'كرداسة', 'Kerdasa', 'EGY'],
            [70, 2, 'أبو النمرس', 'Abu Nomros', 'EGY'],
            [71, 2, 'كفر غطاطي', 'Kafr Ghati', 'EGY'],
            [72, 2, 'منشأة البكاري', 'Manshiyet Al Bakari', 'EGY'],
            [73, 2, 'الدقى', 'Dokki', 'EGY'],
            [74, 2, 'العجوزة', 'Agouza', 'EGY'],
            [75, 2, 'الهرم', 'Haram', 'EGY'],
            [76, 2, 'الوراق', 'Warraq', 'EGY'],
            [77, 2, 'امبابة', 'Imbaba', 'EGY'],
            [78, 2, 'بولاق الدكرور', 'Boulaq Dakrour', 'EGY'],
            [79, 2, 'الواحات البحرية', 'Al Wahat Al Baharia', 'EGY'],
            [80, 2, 'العمرانية', 'Omraneya', 'EGY'],
            [81, 2, 'المنيب', 'Moneeb', 'EGY'],
            [82, 2, 'بين السرايات', 'Bin Alsarayat', 'EGY'],
            [83, 2, 'الكيت كات', 'Kit Kat', 'EGY'],
            [84, 2, 'المهندسين', 'Mohandessin', 'EGY'],
            [85, 2, 'فيصل', 'Faisal', 'EGY'],
            [86, 2, 'أبو رواش', 'Abu Rawash', 'EGY'],
            [87, 2, 'حدائق الأهرام', 'Hadayek Alahram', 'EGY'],
            [88, 2, 'الحرانية', 'Haraneya', 'EGY'],
            [89, 2, 'حدائق اكتوبر', 'Hadayek October', 'EGY'],
            [90, 2, 'صفط اللبن', 'Saft Allaban', 'EGY'],
            [91, 2, 'القرية الذكية', 'Smart Village', 'EGY'],
            [92, 2, 'ارض اللواء', 'Ard Ellwaa', 'EGY'],
            [93, 3, 'ابو قير', 'Abu Qir', 'EGY'],
            [94, 3, 'الابراهيمية', 'Al Ibrahimeyah', 'EGY'],
            [95, 3, 'الأزاريطة', 'Azarita', 'EGY'],
            [96, 3, 'الانفوشى', 'Anfoushi', 'EGY'],
            [97, 3, 'الدخيلة', 'Dekheila', 'EGY'],
            [98, 3, 'السيوف', 'El Soyof', 'EGY'],
            [99, 3, 'العامرية', 'Ameria', 'EGY'],
            [100, 3, 'اللبان', 'El Labban', 'EGY'],
            [101, 3, 'المفروزة', 'Al Mafrouza', 'EGY'],
            [102, 3, 'المنتزه', 'El Montaza', 'EGY'],
            [103, 3, 'المنشية', 'Mansheya', 'EGY'],
            [104, 3, 'الناصرية', 'Naseria', 'EGY'],
            [105, 3, 'امبروزو', 'Ambrozo', 'EGY'],
            [106, 3, 'باب شرق', 'Bab Sharq', 'EGY'],
            [107, 3, 'برج العرب', 'Bourj Alarab', 'EGY'],
            [108, 3, 'ستانلى', 'Stanley', 'EGY'],
            [109, 3, 'سموحة', 'Smouha', 'EGY'],
            [110, 3, 'سيدى بشر', 'Sidi Bishr', 'EGY'],
            [111, 3, 'شدس', 'Shads', 'EGY'],
            [112, 3, 'غيط العنب', 'Gheet Alenab', 'EGY'],
            [113, 3, 'فلمينج', 'Fleming', 'EGY'],
            [114, 3, 'فيكتوريا', 'Victoria', 'EGY'],
            [115, 3, 'كامب شيزار', 'Camp Shizar', 'EGY'],
            [116, 3, 'كرموز', 'Karmooz', 'EGY'],
            [117, 3, 'محطة الرمل', 'Mahta Alraml', 'EGY'],
            [118, 3, 'مينا البصل', 'Mina El-Basal', 'EGY'],
            [119, 3, 'العصافرة', 'Asafra', 'EGY'],
            [120, 3, 'العجمي', 'Agamy', 'EGY'],
            [121, 3, 'بكوس', 'Bakos', 'EGY'],
            [122, 3, 'بولكلي', 'Boulkly', 'EGY'],
            [123, 3, 'كليوباترا', 'Cleopatra', 'EGY'],
            [124, 3, 'جليم', 'Glim', 'EGY'],
            [125, 3, 'المعمورة', 'Al Mamurah', 'EGY'],
            [126, 3, 'المندرة', 'Al Mandara', 'EGY'],
            [127, 3, 'محرم بك', 'Moharam Bek', 'EGY'],
            [128, 3, 'الشاطبي', 'Elshatby', 'EGY'],
            [129, 3, 'سيدي جابر', 'Sidi Gaber', 'EGY'],
            [130, 3, 'الساحل الشمالي', 'North Coast/sahel', 'EGY'],
            [131, 3, 'الحضرة', 'Alhadra', 'EGY'],
            [132, 3, 'العطارين', 'Alattarin', 'EGY'],
            [133, 3, 'سيدي كرير', 'Sidi Kerir', 'EGY'],
            [134, 3, 'الجمرك', 'Elgomrok', 'EGY'],
            [135, 3, 'المكس', 'Al Max', 'EGY'],
            [136, 3, 'مارينا', 'Marina', 'EGY'],
            [137, 4, 'المنصورة', 'Mansoura', 'EGY'],
            [138, 4, 'طلخا', 'Talkha', 'EGY'],
            [139, 4, 'ميت غمر', 'Mitt Ghamr', 'EGY'],
            [140, 4, 'دكرنس', 'Dekernes', 'EGY'],
            [141, 4, 'أجا', 'Aga', 'EGY'],
            [142, 4, 'منية النصر', 'Menia El Nasr', 'EGY'],
            [143, 4, 'السنبلاوين', 'Sinbillawin', 'EGY'],
            [144, 4, 'الكردي', 'El Kurdi', 'EGY'],
            [145, 4, 'بني عبيد', 'Bani Ubaid', 'EGY'],
            [146, 4, 'المنزلة', 'Al Manzala', 'EGY'],
            [147, 4, 'تمي الأمديد', 'tami alamdid', 'EGY'],
            [148, 4, 'الجمالية', 'aljamalia', 'EGY'],
            [149, 4, 'شربين', 'Sherbin', 'EGY'],
            [150, 4, 'المطرية', 'Mataria', 'EGY'],
            [151, 4, 'بلقاس', 'Belqas', 'EGY'],
            [152, 4, 'ميت سلسيل', 'Meet Salsil', 'EGY'],
            [153, 4, 'جمصة', 'Gamasa', 'EGY'],
            [154, 4, 'محلة دمنة', 'Mahalat Damana', 'EGY'],
            [155, 4, 'نبروه', 'Nabroh', 'EGY'],
            [156, 5, 'الغردقة', 'Hurghada', 'EGY'],
            [157, 5, 'رأس غارب', 'Ras Ghareb', 'EGY'],
            [158, 5, 'سفاجا', 'Safaga', 'EGY'],
            [159, 5, 'القصير', 'El Qusiar', 'EGY'],
            [160, 5, 'مرسى علم', 'Marsa Alam', 'EGY'],
            [161, 5, 'الشلاتين', 'Shalatin', 'EGY'],
            [162, 5, 'حلايب', 'Halaib', 'EGY'],
            [163, 5, 'الدهار', 'Aldahar', 'EGY'],
            [164, 6, 'دمنهور', 'Damanhour', 'EGY'],
            [165, 6, 'كفر الدوار', 'Kafr El Dawar', 'EGY'],
            [166, 6, 'رشيد', 'Rashid', 'EGY'],
            [167, 6, 'إدكو', 'Edco', 'EGY'],
            [168, 6, 'أبو المطامير', 'Abu al-Matamir', 'EGY'],
            [169, 6, 'أبو حمص', 'Abu Homs', 'EGY'],
            [170, 6, 'الدلنجات', 'Delengat', 'EGY'],
            [171, 6, 'المحمودية', 'Mahmoudiyah', 'EGY'],
            [172, 6, 'الرحمانية', 'Rahmaniyah', 'EGY'],
            [173, 6, 'إيتاي البارود', 'Itai Baroud', 'EGY'],
            [174, 6, 'حوش عيسى', 'Housh Eissa', 'EGY'],
            [175, 6, 'شبراخيت', 'Shubrakhit', 'EGY'],
            [176, 6, 'كوم حمادة', 'Kom Hamada', 'EGY'],
            [177, 6, 'بدر', 'Badr', 'EGY'],
            [178, 6, 'وادي النطرون', 'Wadi Natrun', 'EGY'],
            [179, 6, 'النوبارية الجديدة', 'New Nubaria', 'EGY'],
            [180, 6, 'النوبارية', 'Alnoubareya', 'EGY'],
            [181, 7, 'الفيوم', 'Fayoum', 'EGY'],
            [182, 7, 'الفيوم الجديدة', 'Fayoum El Gedida', 'EGY'],
            [183, 7, 'طامية', 'Tamiya', 'EGY'],
            [184, 7, 'سنورس', 'Snores', 'EGY'],
            [185, 7, 'إطسا', 'Etsa', 'EGY'],
            [186, 7, 'إبشواي', 'Epschway', 'EGY'],
            [187, 7, 'يوسف الصديق', 'Yusuf El Sediaq', 'EGY'],
            [188, 7, 'الحادقة', 'Hadqa', 'EGY'],
            [189, 7, 'اطسا', 'Atsa', 'EGY'],
            [190, 7, 'الجامعة', 'Algamaa', 'EGY'],
            [191, 7, 'السيالة', 'Sayala', 'EGY'],
            [192, 8, 'طنطا', 'Tanta', 'EGY'],
            [193, 8, 'المحلة الكبرى', 'Al Mahalla Al Kobra', 'EGY'],
            [194, 8, 'كفر الزيات', 'Kafr El Zayat', 'EGY'],
            [195, 8, 'زفتى', 'Zefta', 'EGY'],
            [196, 8, 'السنطة', 'El Santa', 'EGY'],
            [197, 8, 'قطور', 'Qutour', 'EGY'],
            [198, 8, 'بسيون', 'Basion', 'EGY'],
            [199, 8, 'سمنود', 'Samannoud', 'EGY'],
            [200, 9, 'الإسماعيلية', 'Ismailia', 'EGY'],
            [201, 9, 'فايد', 'Fayed', 'EGY'],
            [202, 9, 'القنطرة شرق', 'Qantara Sharq', 'EGY'],
            [203, 9, 'القنطرة غرب', 'Qantara Gharb', 'EGY'],
            [204, 9, 'التل الكبير', 'El Tal El Kabier', 'EGY'],
            [205, 9, 'أبو صوير', 'Abu Sawir', 'EGY'],
            [206, 9, 'القصاصين الجديدة', 'Kasasien El Gedida', 'EGY'],
            [207, 9, 'نفيشة', 'Nefesha', 'EGY'],
            [208, 9, 'الشيخ زايد', 'Sheikh Zayed', 'EGY'],
            [209, 10, 'شبين الكوم', 'Shbeen El Koom', 'EGY'],
            [210, 10, 'مدينة السادات', 'Sadat City', 'EGY'],
            [211, 10, 'منوف', 'Menouf', 'EGY'],
            [212, 10, 'سرس الليان', 'Sars El-Layan', 'EGY'],
            [213, 10, 'أشمون', 'Ashmon', 'EGY'],
            [214, 10, 'الباجور', 'Al Bagor', 'EGY'],
            [215, 10, 'قويسنا', 'Quesna', 'EGY'],
            [216, 10, 'بركة السبع', 'Berkat El Saba', 'EGY'],
            [217, 10, 'تلا', 'Tala', 'EGY'],
            [218, 10, 'الشهداء', 'Al Shohada', 'EGY'],
            [219, 11, 'المنيا', 'Minya', 'EGY'],
            [220, 11, 'المنيا الجديدة', 'Minya El Gedida', 'EGY'],
            [221, 11, 'العدوة', 'El Adwa', 'EGY'],
            [222, 11, 'مغاغة', 'Magagha', 'EGY'],
            [223, 11, 'بني مزار', 'Bani Mazar', 'EGY'],
            [224, 11, 'مطاي', 'Mattay', 'EGY'],
            [225, 11, 'سمالوط', 'Samalut', 'EGY'],
            [226, 11, 'المدينة الفكرية', 'Madinat El Fekria', 'EGY'],
            [227, 11, 'ملوي', 'Meloy', 'EGY'],
            [228, 11, 'دير مواس', 'Deir Mawas', 'EGY'],
            [229, 11, 'ابو قرقاص', 'Abu Qurqas', 'EGY'],
            [230, 11, 'ارض سلطان', 'Ard Sultan', 'EGY'],
            [231, 12, 'بنها', 'Banha', 'EGY'],
            [232, 12, 'قليوب', 'Qalyub', 'EGY'],
            [233, 12, 'شبرا الخيمة', 'Shubra Al Khaimah', 'EGY'],
            [234, 12, 'القناطر الخيرية', 'Al Qanater Charity', 'EGY'],
            [235, 12, 'الخانكة', 'Khanka', 'EGY'],
            [236, 12, 'كفر شكر', 'Kafr Shukr', 'EGY'],
            [237, 12, 'طوخ', 'Tukh', 'EGY'],
            [238, 12, 'قها', 'Qaha', 'EGY'],
            [239, 12, 'العبور', 'Obour', 'EGY'],
            [240, 12, 'الخصوص', 'Khosous', 'EGY'],
            [241, 12, 'شبين القناطر', 'Shibin Al Qanater', 'EGY'],
            [242, 12, 'مسطرد', 'Mostorod', 'EGY'],
            [243, 13, 'الخارجة', 'El Kharga', 'EGY'],
            [244, 13, 'باريس', 'Paris', 'EGY'],
            [245, 13, 'موط', 'Mout', 'EGY'],
            [246, 13, 'الفرافرة', 'Farafra', 'EGY'],
            [247, 13, 'بلاط', 'Balat', 'EGY'],
            [248, 13, 'الداخلة', 'Dakhla', 'EGY'],
            [249, 14, 'السويس', 'Suez', 'EGY'],
            [250, 14, 'الجناين', 'Alganayen', 'EGY'],
            [251, 14, 'عتاقة', 'Ataqah', 'EGY'],
            [252, 14, 'العين السخنة', 'Ain Sokhna', 'EGY'],
            [253, 14, 'فيصل', 'Faysal', 'EGY'],
            [254, 15, 'أسوان', 'Aswan', 'EGY'],
            [255, 15, 'أسوان الجديدة', 'Aswan El Gedida', 'EGY'],
            [256, 15, 'دراو', 'Drau', 'EGY'],
            [257, 15, 'كوم أمبو', 'Kom Ombo', 'EGY'],
            [258, 15, 'نصر النوبة', 'Nasr Al Nuba', 'EGY'],
            [259, 15, 'كلابشة', 'Kalabsha', 'EGY'],
            [260, 15, 'إدفو', 'Edfu', 'EGY'],
            [261, 15, 'الرديسية', 'Al-Radisiyah', 'EGY'],
            [262, 15, 'البصيلية', 'Al Basilia', 'EGY'],
            [263, 15, 'السباعية', 'Al Sibaeia', 'EGY'],
            [264, 15, 'ابوسمبل السياحية', 'Abo Simbl Al Siyahia', 'EGY'],
            [265, 15, 'مرسى علم', 'Marsa Alam', 'EGY'],
            [266, 16, 'أسيوط', 'Assiut', 'EGY'],
            [267, 16, 'أسيوط الجديدة', 'Assiut El Gedida', 'EGY'],
            [268, 16, 'ديروط', 'Dayrout', 'EGY'],
            [269, 16, 'منفلوط', 'Manfalut', 'EGY'],
            [270, 16, 'القوصية', 'Qusiya', 'EGY'],
            [271, 16, 'أبنوب', 'Abnoub', 'EGY'],
            [272, 16, 'أبو تيج', 'Abu Tig', 'EGY'],
            [273, 16, 'الغنايم', 'El Ghanaim', 'EGY'],
            [274, 16, 'ساحل سليم', 'Sahel Selim', 'EGY'],
            [275, 16, 'البداري', 'El Badari', 'EGY'],
            [276, 16, 'صدفا', 'Sidfa', 'EGY'],
            [277, 17, 'بني سويف', 'Bani Sweif', 'EGY'],
            [278, 17, 'بني سويف الجديدة', 'Beni Suef El Gedida', 'EGY'],
            [279, 17, 'الواسطى', 'Al Wasta', 'EGY'],
            [280, 17, 'ناصر', 'Naser', 'EGY'],
            [281, 17, 'إهناسيا', 'Ehnasia', 'EGY'],
            [282, 17, 'ببا', 'beba', 'EGY'],
            [283, 17, 'الفشن', 'Fashn', 'EGY'],
            [284, 17, 'سمسطا', 'Somasta', 'EGY'],
            [285, 17, 'الاباصيرى', 'Alabbaseri', 'EGY'],
            [286, 17, 'مقبل', 'Mokbel', 'EGY'],
            [287, 18, 'بورسعيد', 'PorSaid', 'EGY'],
            [288, 18, 'بورفؤاد', 'Port Fouad', 'EGY'],
            [289, 18, 'العرب', 'Alarab', 'EGY'],
            [290, 18, 'حى الزهور', 'Zohour', 'EGY'],
            [291, 18, 'حى الشرق', 'Alsharq', 'EGY'],
            [292, 18, 'حى الضواحى', 'Aldawahi', 'EGY'],
            [293, 18, 'حى المناخ', 'Almanakh', 'EGY'],
            [294, 18, 'حى مبارك', 'Mubarak', 'EGY'],
            [295, 19, 'دمياط', 'Damietta', 'EGY'],
            [296, 19, 'دمياط الجديدة', 'New Damietta', 'EGY'],
            [297, 19, 'رأس البر', 'Ras El Bar', 'EGY'],
            [298, 19, 'فارسكور', 'Faraskour', 'EGY'],
            [299, 19, 'الزرقا', 'Zarqa', 'EGY'],
            [300, 19, 'السرو', 'alsaru', 'EGY'],
            [301, 19, 'الروضة', 'alruwda', 'EGY'],
            [302, 19, 'كفر البطيخ', 'Kafr El-Batikh', 'EGY'],
            [303, 19, 'عزبة البرج', 'Azbet Al Burg', 'EGY'],
            [304, 19, 'ميت أبو غالب', 'Meet Abou Ghalib', 'EGY'],
            [305, 19, 'كفر سعد', 'Kafr Saad', 'EGY'],
            [306, 20, 'الزقازيق', 'Zagazig', 'EGY'],
            [307, 20, 'العاشر من رمضان', 'Al Ashr Men Ramadan', 'EGY'],
            [308, 20, 'منيا القمح', 'Minya Al Qamh', 'EGY'],
            [309, 20, 'بلبيس', 'Belbeis', 'EGY'],
            [310, 20, 'مشتول السوق', 'Mashtoul El Souq', 'EGY'],
            [311, 20, 'القنايات', 'Qenaiat', 'EGY'],
            [312, 20, 'أبو حماد', 'Abu Hammad', 'EGY'],
            [313, 20, 'القرين', 'El Qurain', 'EGY'],
            [314, 20, 'ههيا', 'Hehia', 'EGY'],
            [315, 20, 'أبو كبير', 'Abu Kabir', 'EGY'],
            [316, 20, 'فاقوس', 'Faccus', 'EGY'],
            [317, 20, 'الصالحية الجديدة', 'El Salihia El Gedida', 'EGY'],
            [318, 20, 'الإبراهيمية', 'Al Ibrahimiyah', 'EGY'],
            [319, 20, 'ديرب نجم', 'Deirb Negm', 'EGY'],
            [320, 20, 'كفر صقر', 'Kafr Saqr', 'EGY'],
            [321, 20, 'أولاد صقر', 'Awlad Saqr', 'EGY'],
            [322, 20, 'الحسينية', 'Husseiniya', 'EGY'],
            [323, 20, 'صان الحجر القبلية', 'san alhajar alqablia', 'EGY'],
            [324, 20, 'منشأة أبو عمر', 'Manshayat Abu Omar', 'EGY'],
            [325, 21, 'الطور', 'Al Toor', 'EGY'],
            [326, 21, 'شرم الشيخ', 'Sharm El-Shaikh', 'EGY'],
            [327, 21, 'دهب', 'Dahab', 'EGY'],
            [328, 21, 'نويبع', 'Nuweiba', 'EGY'],
            [329, 21, 'طابا', 'Taba', 'EGY'],
            [330, 21, 'سانت كاترين', 'Saint Catherine', 'EGY'],
            [331, 21, 'أبو رديس', 'Abu Redis', 'EGY'],
            [332, 21, 'أبو زنيمة', 'Abu Zenaima', 'EGY'],
            [333, 21, 'رأس سدر', 'Ras Sidr', 'EGY'],
            [334, 22, 'كفر الشيخ', 'Kafr El Sheikh', 'EGY'],
            [335, 22, 'وسط البلد كفر الشيخ', 'Kafr El Sheikh Downtown', 'EGY'],
            [336, 22, 'دسوق', 'Desouq', 'EGY'],
            [337, 22, 'فوه', 'Fooh', 'EGY'],
            [338, 22, 'مطوبس', 'Metobas', 'EGY'],
            [339, 22, 'برج البرلس', 'Burg Al Burullus', 'EGY'],
            [340, 22, 'بلطيم', 'Baltim', 'EGY'],
            [341, 22, 'مصيف بلطيم', 'Masief Baltim', 'EGY'],
            [342, 22, 'الحامول', 'Hamol', 'EGY'],
            [343, 22, 'بيلا', 'Bella', 'EGY'],
            [344, 22, 'الرياض', 'Riyadh', 'EGY'],
            [345, 22, 'سيدي سالم', 'Sidi Salm', 'EGY'],
            [346, 22, 'قلين', 'Qellen', 'EGY'],
            [347, 22, 'سيدي غازي', 'Sidi Ghazi', 'EGY'],
            [348, 23, 'مرسى مطروح', 'Marsa Matrouh', 'EGY'],
            [349, 23, 'الحمام', 'El Hamam', 'EGY'],
            [350, 23, 'العلمين', 'Alamein', 'EGY'],
            [351, 23, 'الضبعة', 'Dabaa', 'EGY'],
            [352, 23, 'النجيلة', 'Al-Nagila', 'EGY'],
            [353, 23, 'سيدي براني', 'Sidi Brani', 'EGY'],
            [354, 23, 'السلوم', 'Salloum', 'EGY'],
            [355, 23, 'سيوة', 'Siwa', 'EGY'],
            [356, 23, 'مارينا', 'Marina', 'EGY'],
            [357, 23, 'الساحل الشمالى', 'North Coast', 'EGY'],
            [358, 24, 'الأقصر', 'Luxor', 'EGY'],
            [359, 24, 'الأقصر الجديدة', 'New Luxor', 'EGY'],
            [360, 24, 'إسنا', 'Esna', 'EGY'],
            [361, 24, 'طيبة الجديدة', 'New Tiba', 'EGY'],
            [362, 24, 'الزينية', 'Al ziynia', 'EGY'],
            [363, 24, 'البياضية', 'Al Bayadieh', 'EGY'],
            [364, 24, 'القرنة', 'Al Qarna', 'EGY'],
            [365, 24, 'أرمنت', 'Armant', 'EGY'],
            [366, 24, 'الطود', 'Al Tud', 'EGY'],
            [367, 25, 'قنا', 'Qena', 'EGY'],
            [368, 25, 'قنا الجديدة', 'New Qena', 'EGY'],
            [369, 25, 'ابو طشت', 'Abu Tesht', 'EGY'],
            [370, 25, 'نجع حمادي', 'Nag Hammadi', 'EGY'],
            [371, 25, 'دشنا', 'Deshna', 'EGY'],
            [372, 25, 'الوقف', 'Alwaqf', 'EGY'],
            [373, 25, 'قفط', 'Qaft', 'EGY'],
            [374, 25, 'نقادة', 'Naqada', 'EGY'],
            [375, 25, 'فرشوط', 'Farshout', 'EGY'],
            [376, 25, 'قوص', 'Quos', 'EGY'],
            [377, 26, 'العريش', 'Arish', 'EGY'],
            [378, 26, 'الشيخ زويد', 'Sheikh Zowaid', 'EGY'],
            [379, 26, 'نخل', 'Nakhl', 'EGY'],
            [380, 26, 'رفح', 'Rafah', 'EGY'],
            [381, 26, 'بئر العبد', 'Bir al-Abed', 'EGY'],
            [382, 26, 'الحسنة', 'Al Hasana', 'EGY'],
            [383, 27, 'سوهاج', 'Sohag', 'EGY'],
            [384, 27, 'سوهاج الجديدة', 'Sohag El Gedida', 'EGY'],
            [385, 27, 'أخميم', 'Akhmeem', 'EGY'],
            [386, 27, 'أخميم الجديدة', 'Akhmim El Gedida', 'EGY'],
            [387, 27, 'البلينا', 'Albalina', 'EGY'],
            [388, 27, 'المراغة', 'El Maragha', 'EGY'],
            [389, 27, 'المنشأة', 'almunshaa', 'EGY'],
            [390, 27, 'دار السلام', 'Dar AISalaam', 'EGY'],
            [391, 27, 'جرجا', 'Gerga', 'EGY'],
            [392, 27, 'جهينة الغربية', 'Jahina Al Gharbia', 'EGY'],
            [393, 27, 'ساقلته', 'Saqilatuh', 'EGY'],
            [394, 27, 'طما', 'Tama', 'EGY'],
            [395, 27, 'طهطا', 'Tahta', 'EGY'],
            [396, 27, 'الكوثر', 'Alkawthar', 'EGY']
        ];
    
        foreach ($cities as $city) {
            DB::table('cities')->insert([
                'id' => $city[0],
                'governorate_id' => $city[1],
                'city_name_ar' => $city[2],
                'city_name_en' => $city[3],
                'countrycodealpha3' => $city[4],
            ]);
        }
    }
}